name: todo_list_core
description: 'Todo List Core Package'
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.6.1

dependencies:
  freezed_annotation: ^2.4.4
  intl: ^0.19.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0
